uhh this is makeembed.py, feel free to add changes or such.
cat-dev-group/bot pull request #28
Opened 2021-04-22 19:20 UTC by dannynotsmart

my first time contributing
also i probably forgot a bunch of things which is why YOU GUYS exist

2021-04-22 19:22 UTC, Kronifer reviewed
Did you lint and or use black?

2021-04-22 19:22 UTC, dannynotsmart commented
what are these things

2021-04-22 19:22 UTC, Kronifer commented
CONTRIBUTING.md

2021-04-23 14:42 UTC, Objectivitix requested changes
Pretty good, I suggest two little changes.

1. pull color data from config.yml, but if the issue is approved then soon you'll pull them from constants.py
2. down in the error part, you made the timestamp to be a datetime object. mind putting a strftime and putting that into human-readable format?

thanks!

2021-04-23 15:06 UTC, Objectivitix commented
also, could you add docstrings and make your code comply with pep8?

2021-04-25 18:28 UTC, dannynotsmart commented
BLACK WORKS YAYYYYY 
ok i gota add the color thing

2021-04-25 18:43 UTC, dannynotsmart commented
big update

2021-04-25 18:47 UTC, Objectivitix approved these changes
alright, this looks super good! about the time formatting, it turns out the internal `__str__` dunder method does all that for you. approved!!

2021-04-25 18:54 UTC, dannynotsmart commented
hehe

2021-04-26 02:27 UTC, Kronifer requested changes
If a docstring is unneeded, remove it. Otherwise, change them to comments using the # symbol without quotes

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +""" import dem libs"""
Why is there a docstring here it isnt needed

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +        """ where all the colors can be found in a dict"""
Unneeded docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +
unneeded whitespace

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +        """ ultimate questionare"""
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +        """ where i save the answers"""
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +        """ converting the color keys in data to a list so i can reference it later """
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +        """ the check for self.bot.wait_For """
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +         """ asks the questions, waits for an response. if the msg is cancel the entire process ends """
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +           """ asks the user for the color, checks if the message is a valid key in the data dict. if so, add the color to the answers. """
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +        """ the embed we can make so far """
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +         """ basically asking for if user wants add_field. there is 5 available ones since idk how much to limit. pretty self explanatory but code looks ugly sry"""
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +        """ asks for the timestamp cuz yeahhhh"""
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +         """ asks if they want to send the made embed into another channel. i think this is good if we want like fancy announcements or sum but this is only restricted to admins"""
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +     """ error handelr??"""
Docstring

2021-04-26 02:27 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> + """ sincerely, cat"""
Docstring

2021-04-26 17:57 UTC, dannynotsmart commented
ok i did the changes

2021-04-26 18:00 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +        """ the check for self.bot.wait_For """
Still docstring

2021-04-26 18:00 UTC, Kronifer commented on bot/exts/fun/makeembed.py
> +         """ asks the questions, waits for an response. if the msg is cancel the entire process ends """
Still docstring

2021-04-26 18:02 UTC, Kronifer approved these changes
lgtm, merged

2021-04-26 18:02 UTC, merged